name: parki_dog
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^3.12.1
  google_fonts: ^6.2.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  equatable: ^2.0.5
  firebase_auth: ^5.5.1
  flutter_bloc: ^9.1.0
  bloc: any
  dartz: ^0.10.1
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  cloud_firestore: ^5.6.5
  syncfusion_flutter_datepicker: ^29.1.33
  intl: ^0.19.0
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^7.1.1
  geolocator: ^13.0.3
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  http: ^1.1.0
  google_maps_flutter: ^2.12.0
  widget_to_marker: ^1.0.4
  shared_preferences: ^2.2.1
  geocoding: ^3.0.0
  dropdown_search: ^6.0.2
  easy_debounce: ^2.0.3
  easy_localization: ^3.0.5
  smooth_page_indicator: ^1.1.0
  maps_launcher: ^3.0.0+1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  animated_icon_button: ^1.0.2
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  cloud_functions: ^5.3.4
  image_picker: ^1.0.4
  uuid: ^4.1.0
  change_app_package_name: ^1.1.0
  firebase_storage: ^12.4.4
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.8.0
  pay: ^3.2.0
  fluttertoast: ^8.2.4
  google_mobile_ads: ^5.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  carousel_slider: ^5.0.0
  webview_flutter: ^4.10.0
  # awesome_notifications_core: ^0.8.1
  # awesome_notifications: any
  sign_in_with_apple: ^6.1.4
  flutter_screenutil: ^5.9.0
  auto_size_text: ^3.0.0
  timeline_tile: ^2.0.0
  wheel_picker: ^0.2.1
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^5.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/core/language/
    - assets/translations/
    - assets/icons/
    - assets/images/
    - assets/images/icons/
    - assets/new-images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
