import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:parki_dog/core/theme/app_colors.dart';
import 'package:parki_dog/core/widgets/frost.dart';
import 'package:parki_dog/core/widgets/push_button.dart';
import 'package:parki_dog/core/widgets/search_field.dart';

import '../../features/lang/lang_cubit.dart';
import '../../features/lang/lang_state.dart';

class BreedSelector extends StatefulWidget {
  const BreedSelector({super.key, this.selectionMode = 'single', this.initialValue});

  final String selectionMode;
  final List<String>? initialValue;

  @override
  State<BreedSelector> createState() => _BreedSelectorState();
}

class _BreedSelectorState extends State<BreedSelector> {
  List<String> selected = [];

  late final List<String> breeds;
  late List<String> searchedBreeds;

  @override
  void initState() {
    super.initState();
    breeds = const [
      'Affenpinscher',
      'Afghan Hound',
      'Airedale Terrier',
      'Akita',
      'Alaskan Malamute',
      'Alpine Dachsbracke',
      'American Akita',
      'American Cocker Spaniel',
      'American Foxhound',
      'American Staffordshire Terrier',
      'American Water Spaniel',
      'Appenzell Cattle',
      'Ariege Pointing Dog',
      'Ariegeois',
      'Artois Hound',
      'Atlas Mountain (Aidi)',
      'Australian Cattle Dog',
      'Australian Kelpie',
      'Australian Shepherd',
      'Australian Silky Terrier',
      'Australian Stumpy Tail Cattle Dog',
      'Australian Terrier',
      'Austrian  Pinscher',
      'Austrian Black And Tan Hound',
      'Auvergne Pointer',
      'Azawakh',
      'Basenji',
      'Basset Fauve De Bretagne',
      'Basset Hound',
      'Bavarian Mountain Scent Hound',
      'Beagle',
      'Beagle Harrier',
      'Bearded Collie',
      'Bedlington Terrier',
      'Belgian Shepherd',
      'Bergamasco Shepherd',
      'Berger De Beauce',
      'Bernese Mountain Dog',
      'Bichon Frise',
      'Billy',
      'Black And Tan Coonhound',
      'Bloodhound',
      'Blue Gascony Basset',
      'Blue Gascony Griffon',
      'Blue Picardy Spaniel',
      'Bohemian Shepherd',
      'Bohemian Wirehaired Pointing Griffon',
      'Bolognese',
      'Border Collie',
      'Border Terrier',
      'Borzoi',
      'Croatian Shepherd',
      'Barak',
      'Boston Terrier',
      'Bourbonnais Pointing Dog',
      'Bouvier Des Ardennes',
      'Bouvier Des Flandres',
      'Boxer',
      'Brazilian Terrier',
      'Brazilian Tracker',
      'Briard',
      'Briquet Griffon Vendeen',
      'Brittany Spaniel',
      'Broholmer',
      'Bull Terrier',
      'Bulldog',
      'Bullmastiff',
      'Burgos Pointing Dog',
      'Cairn Terrier',
      'Canaan Dog',
      'Canadian Eskimo Dog',
      'Canarian Warren Hound',
      'Castro Laboreiro Dog',
      'Catalan Sheepdog',
      'Caucasian Shepherd',
      'Cavalier King Charles Spaniel',
      'Central Asia Shepherd',
      'Cesky Terrier',
      'Chesapeake Bay Retriever',
      'Chihuahua',
      'Chinese Crested Dog',
      'Chow Chow',
      'Cimarrón Uruguayo',
      'Cirneco Dell\'Etna',
      'Clumber Spaniel',
      'Styrian Hound',
      'Collie Rough',
      'Collie Smooth',
      'Continental Bulldog',
      'Continental Toy Spaniel',
      'Coton De Tulear',
      'Croatian Shepherd',
      'Curly Coated Retriever',
      'Czechoslovakian Wolfdog',
      'Dachshund',
      'Dalmatian',
      'Dandie Dinmont Terrier',
      'Danish-Swedish Farmdog',
      'Deerhound',
      'Deutsch Langhaar',
      'Deutsch Stichelhaar',
      'Dobermann',
      'Dogo Argentino',
      'Dogue De Bordeaux',
      'Drentsche Partridge Dog',
      'Drever',
      'Dutch Schapendoes',
      'Dutch Shepherd',
      'Dutch Smoushond',
      'East Siberian Laika',
      'English Cocker Spaniel',
      'English Foxhound',
      'English Pointer',
      'English Setter',
      'English Springer Spaniel',
      'English Toy Terrier (Black &Tan)',
      'Entlebuch Cattle Dog',
      'Estonian Hound',
      'Estrela Mountain Dog',
      'Eurasian',
      'Fawn Brittany Griffon',
      'Field Spaniel',
      'Fila Brasileiro',
      'Finnish Hound',
      'Finnish Lapponian Dog',
      'Finnish Spitz',
      'Flat Coated Retriever',
      'Fox Terrier (Smooth)',
      'Fox Terrier (Wire)',
      'French Bulldog',
      'French Pointing Dog',
      'French Spaniel',
      'French Tricolour Hound',
      'French Water Dog',
      'French White & Black Hound',
      'French White And Orange Hound',
      'Frisian Water Dog',
      'Gascon Saintongeois',
      'German Hound',
      'German Hunting Terrier',
      'German Pinscher',
      'German Shepherd',
      'German Shorthaired Pointing Dog',
      'German Spaniel',
      'German Spitz',
      'German Wirehaired Pointing Dog',
      'Giant Schnauzer',
      'Golden Retriever',
      'Gordon Setter',
      'Grand Basset Griffon Vendeen',
      'Grand Griffon Vendeen',
      'Great Anglo-French Tricolour Hound',
      'Great Anglo-French White & Orange Hound',
      'Great Anglo-French White And Black Hound',
      'Great Dane',
      'Great Gascony Blue',
      'Great Swiss Mountain Dog',
      'Greenland Dog',
      'Greyhound',
      'Griffon Belge',
      'Griffon Bruxellois',
      'Griffon Nivernais',
      'Halden Hound',
      'Hamiltonstövare',
      'Hanoverian Scent Hound',
      'Harrier',
      'Havanese',
      'Hellenic Hound',
      'Hokkaido',
      'Hovawart',
      'Hungarian Greyhound',
      'Transylvanian Hound',
      'Vizsla',
      'Hungarian Wirehaired Pointer',
      'Hygen Hound',
      'Ibizan Podenco',
      'Icelandic Sheepdog',
      'Irish Glen Of Imaal Terrier',
      'Irish Red And White Setter',
      'Irish Red Setter',
      'Irish Soft Coated Wheaten Terrier',
      'Irish Terrier',
      'Irish Water Spaniel',
      'Irish Wolfhound',
      'Istrian Shorthaired Hound',
      'Istrian Wirehaired Hound',
      'Italian Cane Corso',
      'Italian Pointing Dog',
      'Italian Roughhaired Segugio',
      'Italian Shorthaired Segugio',
      'Italian Sighthound',
      'Italian Spinone',
      'Italian Volpino',
      'Jämthund',
      'Jack Russell Terrier',
      'Japanese Chin',
      'Japanese Spitz',
      'Japanese Terrier',
      'Kai',
      'Kangal Shepherd',
      'Karelian Bear Dog',
      'Karst Shepherd',
      'Kerry Blue Terrier',
      'King Charles Spaniel',
      'Kintamani-Bali Dog',
      'Kishu',
      'Kleiner Münsterländer',
      'Komondor',
      'Korea Jindo Dog',
      'Kromfohrländer',
      'Kuvasz',
      'Labrador Retriever',
      'Laika',
      'Lakeland Terrier',
      'Lancashire Heeler',
      'Landseer (European Continental Type)',
      'Lapponian Herder',
      'Large Munsterlander',
      'Leonberger',
      'Lhasa Apso',
      'Little Lion Dog',
      'Pyrenean Sheepdog',
      'Majorca Mastiff',
      'Majorca Shepherd',
      'Maltese',
      'Manchester Terrier',
      'Maremma And The Abruzzes Sheepdog',
      'Mastiff',
      'Anglo-French Hound',
      'Miniature American Shepherd',
      'Miniature Bull Terrier',
      'Miniature Pinscher',
      'Miniature Schnauzer',
      'Montenegrin Mountain Hound',
      'Mudi',
      'Neapolitan Mastiff',
      'Nederlandse Kooikerhondje',
      'Newfoundland',
      'Norfolk Terrier',
      'Norman Artesien Basset',
      'Norrbottenspitz',
      'Norwegian Buhund',
      'Norwegian Elkhound Black',
      'Norwegian Elkhound Grey',
      'Norwegian Hound',
      'Norwegian Lundehund',
      'Norwich Terrier',
      'Nova Scotia Duck Tolling Retriever',
      'Old Danish Pointing Dog',
      'Old English Sheepdog',
      'Otterhound',
      'Parson Russell Terrier',
      'Pekingese',
      'Peruvian Hairless Dog',
      'Petit Basset Griffon Vendeen',
      'Petit Brabançon',
      'Pharaoh Hound',
      'Picardy Sheepdog',
      'Picardy Spaniel',
      'Poitevin',
      'Polish Greyhound',
      'Polish Hound',
      'Polish Hunting Dog',
      'Polish Lowland Sheepdog',
      'Pont-Audemer Spaniel',
      'Poodle',
      'Porcelaine',
      'Portuguese Pointing Dog',
      'Portuguese Sheepdog',
      'Portuguese Podengo',
      'Portuguese Water Dog',
      'Posavatz Hound',
      'Prague Ratter',
      'Presa Canario',
      'Pudelpointer',
      'Pug',
      'Puli',
      'Pumi',
      'Pyrenean Mastiff',
      'Pyrenean Mountain Dog',
      'Pyrenean Sheepdog',
      'Rafeiro Of Alentejo',
      'Rhodesian Ridgeback',
      'Romagna Water Dog',
      'Romanian Bucovina Shepherd',
      'Romanian Carpathian Shepherd',
      'Romanian Mioritic Shepherd',
      'Rottweiler',
      'Russian Black Terrier',
      'Russian Toy',
      'Saarloos Wolfhond',
      'Saint Germain Pointer',
      'Saint Miguel Cattle Dog',
      'Saluki',
      'Samoyed',
      'Šarplaninac',
      'Schillerstövare',
      'Schipperke',
      'Schnauzer',
      'Scottish Terrier',
      'Sealyham Terrier',
      'Segugio Maremmano',
      'Serbian Hound',
      'Serbian Tricolour Hound',
      'Shar Pei',
      'Shetland Sheepdog',
      'Shiba',
      'Shih Tzu',
      'Shikoku',
      'Siberian Husky',
      'Skye Terrier',
      'Sloughi',
      'Slovakian Chuvach',
      'Slovakian Hound',
      'Smålandsstövare',
      'Small Blue Gascony',
      'Small Swiss Hound',
      'South Russian Shepherd',
      'Spanish Greyhound',
      'Spanish Hound',
      'Spanish Mastiff',
      'Spanish Water Dog',
      'St. Bernard',
      'Stabijhoun',
      'Staffordshire Bull Terrier',
      'Sussex Spaniel',
      'Swedish Lapphund',
      'Swedish Vallhund',
      'Swiss Hound',
      'Taiwan Dog',
      'Tatra Shepherd',
      'Thai Bangkaew Dog',
      'Thai Ridgeback Dog',
      'Tibetan Mastiff',
      'Tibetan Spaniel',
      'Tibetan Terrier',
      'Tornjack',
      'Tosa',
      'Transmontano Mastiff',
      'Tyrolean Hound',
      'Valencian Terrier',
      'Weimaraner',
      'Welsh Corgi (Cardigan)',
      'Welsh Corgi (Pembroke)',
      'Welsh Springer Spaniel',
      'Welsh Terrier',
      'West Highland White Terrier',
      'West Siberian Laika',
      'Westphalian Dachsbracke',
      'Whippet',
      'White Swiss Shepherd',
      'Wirehaired Pointing Griffon Korthals',
      'Wirehaired Slovakian Pointer',
      'Xoloitzcuintle',
      'Yakutian Laika',
      'Yorkshire Terrier',
    ];
    searchedBreeds = breeds;

    if (widget.initialValue != null) {
      selected.addAll(widget.initialValue!);
    }
  }

  void toggleSelectionMultiple(String value) {
    if (selected.contains(value)) {
      selected.remove(value);
    } else {
      selected.add(value);
    }

    setState(() {});
  }

  bool _isSelected(String value) {
    return selected.contains(value) ? true : false;
  }

  void onSearch(String value) {
    searchedBreeds = breeds.where((element) => element.toLowerCase().contains(value.toLowerCase())).toList();

    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Frost(
      child: BlocBuilder<LangCubit, LangState>(builder: (context, state) {
        return Scaffold(
          // extendBody: true,
          backgroundColor: Colors.black.withOpacity(0.6),
          appBar: AppBar(
            toolbarHeight: 200,
            automaticallyImplyLeading: false,
            backgroundColor: Colors.transparent,
            elevation: 0,
            title: SizedBox(
              height: 120,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.end,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'Select dog breed',
                    style: TextStyle(
                      fontSize: 24,
                      fontWeight: FontWeight.w600,
                      color: AppColors.secondary,
                    ),
                  ),
                  const SizedBox(height: 16),
                  SearchField(
                    placeholder: 'Search for a breed',
                    onChanged: onSearch,
                  ),
                ],
              ),
            ),
          ),
          body: ListView.builder(
            padding: const EdgeInsets.symmetric(horizontal: 24),
            itemBuilder: (context, index) {
              return CupertinoButton(
                alignment: Alignment.centerLeft,
                padding: const EdgeInsets.symmetric(vertical: 12),
                onPressed: () {
                  if (widget.selectionMode == 'multiple') {
                    toggleSelectionMultiple(searchedBreeds[index]);
                  } else {
                    Navigator.pop(context, searchedBreeds[index]);
                  }
                },
                child: Text(searchedBreeds[index],
                    style: TextStyle(
                      color: _isSelected(searchedBreeds[index]) ? AppColors.secondary : Colors.white,
                      fontSize: 18,
                    )),
              );
            },
            itemCount: searchedBreeds.length,
          ),
          bottomNavigationBar: Padding(
            padding: const EdgeInsets.fromLTRB(32, 16, 32, 16),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                widget.selectionMode == 'multiple'
                    ? PushButton(
                        text: 'OK',
                        textColor: AppColors.secondary,
                        borderColor: AppColors.secondary,
                        onPress: () =>
                            Navigator.pop(context, selected.toString().replaceAll('[', '').replaceAll(']', '')),
                        fill: false,
                        color: Colors.transparent,
                      )
                    : const SizedBox.shrink(),
                SizedBox(height: widget.selectionMode == 'multiple' ? 24 : 0),
                FloatingActionButton.small(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  elevation: 0,
                  backgroundColor: Colors.transparent,
                  foregroundColor: Colors.white,
                  shape: const CircleBorder(
                    side: BorderSide(color: Colors.white),
                  ),
                  child: const Icon(Icons.close),
                ),
              ],
            ),
          ),
          // extendBody: true,
        );
      }),
    );
  }
}
